### ISSUE TITLE
20231027 - day 93

### ISSUE THREAD

**Issue by tjkpolisher** [tjkpolisher/Bootcamp_TIL#93]
# 좋았던 점
* 실제 회사에서 있을 법한 긴급한 업무 그리고 그에 대처하는 시나리오를 실습해봤습니다. 음 뭐랄까... 이번에도 연구실 시절 PTSD가 떠올라서 불안하고 초조하기는 했지만, 그래도 실무에서의 희미한 기억들을 되짚어가며 마인드 컨트롤을 하고 동시에 새로운 노하우와 방법론을 배울 수 있어서 신선하고 재밌었습니다.

# 아쉬웠던 점
* 최대한 시간을 엄수하려고 했는데, 그래도 겪어보지 않은 상황이다 보니 시간 제한이 타이트하기도 하고, 올바르지 못한 대처가 나오기도 했습니다. 회사에 갔을 때는 같은 실수를 반복하지 않기를 바라며....

# 배운 점
### 테스트 전 - deploy를 지정하지 않고 도커컴포즈만 실행했을 때
로드 테스트 전의 모습입니다. deploy는 아무것도 지정하지 않고 제 블로그만 실행하면 아래와 같이 리소스를 소모합니다.
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/3af27e63-66f4-44ff-9692-407f11bdafc1)
지금부터 여기에 각종 제약조건을 걸고 시작해보도록 하겠습니다. 일단 스케일 아웃을 시험하기 위해 다음 명령어를 통해 스케일을 조정하겠습니다. 1~5 정도로 시험하면 되겠지 싶습니다.
```Bash
$ docker compose up -d --scale tjkpolisher=${원하는 스케일}
```  
그러고 나면 도커컴포즈에 지정한 프록시 URL을 hosts 파일에서 수정합니다. 수정된 URL로도 잘 접속됨을 확인했다면, 스케일을 변경할 때마다 nGrinder에서 테스트를 진행합니다.
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/28f00425-5052-4dc4-a586-c0eec6cd3e99)
먼저 도커 컴포즈 파일에서 deploy 탭에 제약조건을 걸어줍니다. 현재 걸려 있는 제약 조건은 deploy를 지정하지 않았을 때를 기준으로 합니다.
```Yaml
tjkpolisher:
    image: tjkpolisher/tjkpolisher.github.io
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=tjk.com
      - VIRTUAL_PORT=80
    deploy:
      mode: replicated
      replicas: 1  # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 6M
```  
그리고 먼저 스케일 1일 때를 기준으로 시험을 합니다.  
Ramp-up 옵션을 켜고 쓰레드를 선택합니다. 처음부터 부하를 풀로 주는 것보다는 서서히 부하를 주면서 어느 시점에 오류가 발생하는지 확인하기 편하기 때문에 웬만하면 램프-업 옵션을 주는 것이 좋습니다. Initial Sleep Time은 1000ms~5000ms를 권장한다고 하네요. 인터벌은 여기서 1000ms로 줬지만, 상황에 따라 그 10배인 10000ms로도 줄 수 있습니다.
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/7b4fa8f3-afd3-4d3d-90f6-5b0eb9a7018b)
#### 하드웨어 사양 고정 + 스케일 변화
* 스케일 1
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/78393616-72f1-4357-a79f-9fff655fdbd2)
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/80336864-85c9-40cb-8fc1-5aed41c82483)
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/6b600f28-4089-4581-a51c-cb3c0c0c5451)

* 스케일 2
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/b002f14c-56b0-49eb-9224-78d320d2c8f2)  
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/dd691fa2-541d-42ad-b259-ab295eb4d3c7)
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/e728850a-4b2e-4247-8da7-0f7cc17cc9c0)

* 스케일 3
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/73819515-fdea-4bef-9b40-da3fd598c094)
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/05edb4f6-d80a-45c6-9cbb-d4d3f161e0d5)
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/925c1610-a3ff-4bca-bcec-3c54147af95d)

* 스케일 4
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/8d68712c-6249-46b3-8f03-147ddb30202d)
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/f2a5cf71-b2b5-4a8e-8aee-5caf9655268c)
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/d533e881-ed97-401f-8b1a-5657ddd2f8b4)

### `sleep`의 도입
이렇게까지 했는데 무슨 짓을 해도 아웃스케일로는 안정성을 도모할 수 없을 것 같습니다. 그래서 스크립트에 `sleep()` 함수를 추가하는 방법을 사용하겠습니다.
다시 설정 칸으로 돌아가봅시다. 스크립트 칸의 오른쪽의 R 버튼을 클릭합니다.
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/4dac9fc6-7526-48a8-870b-4b626b0c637f)
여기로 들어오면 자바 구문의 스크립트가 뜹니다. 우리가 바꿀 것은 맨 아래에 있는 `test()` 함수입니다. 여기에 `grinder.sleep()`을 추가합니다. 괄호 안에 들어가는 숫자는 밀리세컨드 단위로, 테스트를 돌리는 와중에 일정 시간의 유예기간을 둬서 CPU에 가해지는 부하(load)를 제어하는 역할을 합니다. 저는 1초의 유예기간을 줄 것이기 때문에 1000밀리세컨드를 뜻하는 1000을 입력했습니다. 저장을 누르고 나옵니다.
> 웬만한 컴퓨터에서는 이렇게 `sleep()`을 넣는 것이 좋습니다. 회사에서나 쓸 법한 초고사양 서버가 아닌 이상 nGrinder에서 무한루프를 통해 테스트를 돌리며 컴퓨터에 부하를 걸면 오류가 생기고 버벅일 수 밖에 없기 때문입니다.  

![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/12b9e865-2c2d-40f1-b1cd-78bd4eb26e36)
이후로는 똑같습니다. 실행을 누르고 결과를 보면 됩니다. 현재 테스트 환경은 스케일 3에 CPU는 0.04(즉, 최대 4%), RAM은 50MB로 제한한 상태입니다.
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/abdc3f2f-263a-4538-9e40-025b2a60a45c)  
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/5f291a49-4e4b-4261-9a00-b09886056a4d)
결과를 보니 예전과 달리 처음 1분간은 선형적으로 TPS가 증가하고, 이후로는 150에서 매우 안정적으로 유지되는 것을 볼 수 있습니다. 응답 속도도 일정하고, 오류가 발생하지 않습니다.
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/f19c530c-e381-40fd-afdc-784cc3aca342)
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/f5e0d4c9-42e6-4539-9975-0e31577adeb4)
![image](https://github.com/tjkpolisher/Bootcamp_TIL/assets/80250150/bada37ed-0cea-4bf7-9904-9642c5e0315f)

## 보고서 작성 관련 팁
* 보고서는 두괄식으로 작성하는 것이 좋습니다. 테스트 결과 등의 결론을 먼저 배치하지 않으면, 이후에 들어가는 코드와 사진 떄문에 가독성이 떨어질 수도 있기 때문입니다.
* 테스트 조건 등은 별도의 링크와 문서를 이용하는 것도 좋은 방법입니다.
* 

# 앞으로 바라는 점
*
